basePath: /
definitions:
  dto.FirebaseLoginRequest:
    properties:
      token:
        type: string
    type: object
  dto.UserLoginResponse:
    properties:
      data:
        $ref: '#/definitions/dto.UserResponseDTO'
      message:
        type: string
      status:
        type: string
    type: object
  dto.UserResponseDTO:
    properties:
      createdAt:
        type: string
      email:
        type: string
      firebaseId:
        type: string
      id:
        type: string
      isActive:
        type: boolean
      lastLogin:
        type: string
      roles:
        $ref: '#/definitions/models.Role'
      username:
        type: string
    type: object
  models.Role:
    properties:
      id:
        type: string
      name:
        type: string
    type: object
  utils.ErrorResponse:
    properties:
      errors: {}
      message:
        type: string
      status:
        type: string
    type: object
host: http://192.168.100.247:7070
info:
  contact: {}
  description: API documentation for recipe API
  title: Course Online API
  version: "1.0"
paths:
  /api/auth/firebase-login:
    post:
      consumes:
      - application/json
      description: Login user with token from Firebase Authentication
      parameters:
      - description: Firebase Token
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/dto.FirebaseLoginRequest'
      produces:
      - application/json
      responses:
        "200":
          description: Login success
          schema:
            $ref: '#/definitions/dto.UserLoginResponse'
        "400":
          description: Invalid request
          schema:
            $ref: '#/definitions/utils.ErrorResponse'
        "401":
          description: Invalid token
          schema:
            $ref: '#/definitions/utils.ErrorResponse'
        "500":
          description: Internal server error
          schema:
            $ref: '#/definitions/utils.ErrorResponse'
      summary: Login with Firebase Token
      tags:
      - Auth
swagger: "2.0"
