basePath: /
definitions:
  dto.FirebaseLoginRequest:
    properties:
      token:
        type: string
    type: object
host: http://192.168.100.247:7070
info:
  contact: {}
  description: API documentation for recipe API
  title: Course Online API
  version: "1.0"
paths:
  /auth/firebase-login:
    post:
      consumes:
      - application/json
      description: This endpoint allows users to log in using a Firebase authentication
        token (e.g., Google Sign-In).
      parameters:
      - description: Bearer Firebase ID Token
        in: header
        name: Authorization
        type: string
      - description: Firebase token in JSON body (optional)
        in: body
        name: body
        schema:
          $ref: '#/definitions/dto.FirebaseLoginRequest'
      produces:
      - application/json
      responses:
        "200":
          description: Login successful
          schema:
            additionalProperties: true
            type: object
        "400":
          description: Invalid request body
          schema:
            additionalProperties:
              type: string
            type: object
        "401":
          description: Unauthorized or invalid Firebase token
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Login user using Firebase ID Token
      tags:
      - Authentication
swagger: "2.0"
